# Generated by Django 2.2.6 on 2019-11-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='start_time',
        ),
    ]
