# Generated by Django 2.2.6 on 2019-11-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_auto_20191119_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_type',
            field=models.BooleanField(blank=True, null=True, verbose_name='auction_type'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='name'),
        ),
    ]
