# Generated by Django 2.2.6 on 2019-11-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0003_auto_20191119_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_type',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='auction_type'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True, default='description', max_length=256, null=True, verbose_name='description'),
        ),
    ]
