# Generated by Django 2.2.6 on 2019-11-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0004_auto_20191119_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_type',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='auction_type'),
        ),
    ]
