# Generated by Django 2.2.6 on 2019-11-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0008_auto_20191119_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='highest_bidder',
            field=models.CharField(blank=True, default='no bids', max_length=256, null=True, verbose_name='bidder'),
        ),
    ]
