# Generated by Django 2.2.6 on 2019-11-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0009_items_highest_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='admin',
            field=models.CharField(default='no admin', max_length=256),
        ),
    ]
