# Generated by Django 2.2.6 on 2019-11-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_auto_20191118_1617'),
        ('auction_app', '0011_auto_20191119_0427'),
    ]

    operations = [
    ]
