# Generated by Django 2.2.6 on 2019-11-22 16:30

import auction_app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0012_merge_20191122_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_type',
        ),
        migrations.AddField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=auction_app.models.one_hour_hence, verbose_name='end_time'),
        ),
        migrations.AddField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start_time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(default='description', max_length=256, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='name',
            field=models.CharField(default='Auction name', max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(default='item description', max_length=256, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='items',
            name='highest_bidder',
            field=models.CharField(default='no bids', max_length=256, verbose_name='bidder'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6, verbose_name='price'),
        ),
    ]
