# Generated by Django 2.2.6 on 2019-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0013_auto_20191122_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_id',
            field=models.IntegerField(default=-1, verbose_name='auction_id'),
        ),
    ]
