# Generated by Django 2.2.6 on 2019-11-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0014_auction_auction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_id',
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='image'),
        ),
    ]
