# Generated by Django 2.2.6 on 2019-12-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0016_auto_20191128_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='admin'),
        ),
    ]
