# Generated by Django 2.2.6 on 2019-12-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0017_user_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
    ]
