# Generated by Django 2.2.6 on 2019-12-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0018_remove_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='live_auction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
